### ISSUE TITLE
Is there a "pretty" version of the json response in the public API?

### ISSUE THREAD

**Issue by daviortega** [bitspill/oip#21]
Could we have something like this:

https://api.oip.io/oip/o5/record/mapping/tmpl_90BD561D?pretty=true

or something like that?

The response just needs to pass through something like `JSON.stringify(payload, null, ' ')`

**Comment by bitspill** [comment]
> The response just needs to pass through something like `JSON.stringify(payload, null, ' ')`

Would have been nice if it were that easy 😉 

PR Submitted
